fix: format zsh autoloaded functions
Signed-off-by: Vladislav Doster <mvdoster@gmail.com>

diff --git a/zsh/.config/zsh/functions/bootstrap-macos b/zsh/.config/zsh/functions/bootstrap-macos
--- a/zsh/.config/zsh/functions/bootstrap-macos
+++ b/zsh/.config/zsh/functions/bootstrap-macos
@@ -18,7 +18,6 @@ local HOST_UUID=$(ioreg -d2 -c IOPlatformExpertDevice | awk -F\" '/IOPlatformUUI
 #   ❯ strings /System/Library/PrivateFrameworks/TCC.framework/Versions/Current/Resources/tccd | grep "^kTCCService[A-Z a-z]" | sort | uniq
 # Ask for the administrator password upfront
 
-
 sudo -v
 # Remove the auto-hiding Dock delay
 defaults write com.apple.dock autohide-delay -int 0
@@ -64,15 +63,7 @@ defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
 # Sources:
 #     https://www.reddit.com/r/apple/comments/5rfdj6/pro_tip_significantly_improve_bluetooth_audio/
 #     https://apple.stackexchange.com/questions/40259/bluetooth-audio-problems-on-a-macbook
-for bitpool_param (
-  "Negotiated Bitpool"
-  "Negotiated Bitpool Max"
-  "Negotiated Bitpool Min"
-  "Apple Bitpool Max (editable)"
-  "Apple Bitpool Min (editable)"
-  "Apple Initial Bitpool (editable)"
-  "Apple Initial Bitpool Min (editable)"
-  ); do
+for bitpool_param in "Negotiated Bitpool" "Negotiated Bitpool Max" "Negotiated Bitpool Min" "Apple Bitpool Max (editable)" "Apple Bitpool Min (editable)" "Apple Initial Bitpool (editable)" "Apple Initial Bitpool Min (editable)"; do
   defaults write com.apple.BluetoothAudioAgent "${bitpool_param}" -int 80
 done
 # Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
@@ -133,15 +124,15 @@ defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
 # sudo command find ~/ -name ".DS_Store" -print -delete || true
 # sudo find ~/ -name ".DS_Store" -type f -print -exec sudo rm -f {} \;
 /usr/libexec/PlistBuddy \
-  -c "Delete :StandardViewOptions:ColumnViewOptions:ColumnShowIcons"    \
-  -c "Delete :StandardViewOptions:ColumnViewOptions:FontSize"           \
-  -c "Delete :StandardViewOptions:ColumnViewOptions:ShowPreview"        \
+  -c "Delete :StandardViewOptions:ColumnViewOptions:ColumnShowIcons" \
+  -c "Delete :StandardViewOptions:ColumnViewOptions:FontSize" \
+  -c "Delete :StandardViewOptions:ColumnViewOptions:ShowPreview" \
   -c "Delete :StandardViewOptions:ColumnViewOptions:ShowIconThumbnails" \
-  -c "Delete :StandardViewOptions:ColumnViewOptions:ArrangeBy"          \
+  -c "Delete :StandardViewOptions:ColumnViewOptions:ArrangeBy" \
   ~/Library/Preferences/com.apple.finder.plist || true
 /usr/libexec/PlistBuddy \
   -c "Add :StandardViewOptions:ColumnViewOptions:ColumnShowIcons    bool    true" \
-  -c "Add :StandardViewOptions:ColumnViewOptions:FontSize           integer 16"   \
+  -c "Add :StandardViewOptions:ColumnViewOptions:FontSize           integer 16" \
   -c "Add :StandardViewOptions:ColumnViewOptions:ShowPreview        bool    true" \
   -c "Add :StandardViewOptions:ColumnViewOptions:ShowIconThumbnails bool    true" \
   -c "Add :StandardViewOptions:ColumnViewOptions:ArrangeBy          string  dnam" \
@@ -179,33 +170,17 @@ for app in "Safari" "Vivaldi Snapshot" "kitty"; do
   [[ -e /Applications/${app}.app ]] && {
     dockutil --remove "${app}" --allhomes --no-restart
     dockutil --add "/Applications/${app}.app" --allhomes --no-restart --position end --section apps
-  } && echo "==> ${app} added to dock" || \
-    echo "Error: ${app} not found"
+  } && echo "==> ${app} added to dock" \
+    || echo "Error: ${app} not found"
 done
 for app in "Messages" "Mail" "Music" "Preview" "Utilities/Activity Monitor" "System Settings"; do
   [[ -e /System/Applications/${app}.app ]] && {
     dockutil --remove "$(basename ${app})" --allhomes --no-restart
     dockutil --add "/System/Applications/${app}.app" --allhomes --no-restart --section apps
-  } &> /dev/null && echo "==> ${app} added to dock" || \
-    echo "Error: ${app} not found"
+  } &> /dev/null && echo "==> ${app} added to dock" \
+    || echo "Error: ${app} not found"
 done
-for app (
-  "Activity Monitor"
-  "Address Book"
-  "Calendar"
-  "Contacts"
-  "Dock"
-  "Finder"
-  "Mail"
-  "Messages"
-  "Photos"
-  "Safari"
-  "SystemUIServer"
-  "Terminal"
-  "Transmission"
-  "cfprefsd"
-  "iCal"
-  ); do
+for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "Dock" "Finder" "Mail" "Messages" "Photos" "Safari" "SystemUIServer" "Terminal" "Transmission" "cfprefsd" "iCal"; do
   killall "${app}" &> /dev/null || true
 done
 
